//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_employee
    {
        public int id { get; set; }
        public string number { get; set; }
        public string name { get; set; }
        public string sex { get; set; }
        public Nullable<int> orgnization_id { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string profession { get; set; }
        public Nullable<int> education { get; set; }
        public string professional { get; set; }
        public string job_number { get; set; }
        public string job_group { get; set; }
        public Nullable<System.DateTime> job_date { get; set; }
        public Nullable<int> job_nature { get; set; }
        public Nullable<int> age { get; set; }
        public string graduate_institutions { get; set; }
        public string email { get; set; }
        public string mobile_phone { get; set; }
        public string post { get; set; }
        public string major { get; set; }
        public string identity_card { get; set; }
        public Nullable<int> bank_class { get; set; }
        public string salary_bank { get; set; }
        public string qq { get; set; }
        public string unit { get; set; }
        public string short_no { get; set; }
        public string zip_code { get; set; }
        public string office_fax { get; set; }
        public string office_tel { get; set; }
        public string office_phone { get; set; }
        public string office_email { get; set; }
        public string office_address { get; set; }
        public string office_s_phone { get; set; }
        public Nullable<int> office_class { get; set; }
        public Nullable<int> flag { get; set; }
        public Nullable<System.DateTime> flag_date { get; set; }
        public string flag_cause { get; set; }
        public string flag_direction { get; set; }
        public string native_place { get; set; }
        public string home_zip_code { get; set; }
        public string home_address { get; set; }
        public string home_tel { get; set; }
        public Nullable<int> government { get; set; }
        public Nullable<int> citizenship { get; set; }
        public Nullable<int> nation { get; set; }
        public string code_cn { get; set; }
        public Nullable<int> deleteflag { get; set; }
        public Nullable<int> FCompanyId { get; set; }
        public Nullable<int> FFlag { get; set; }
        public string FIOrgNum { get; set; }
        public string FINum { get; set; }
        public string FLogistics { get; set; }
        public string FDistributionPoint { get; set; }
        public string FNo { get; set; }
    
        public virtual base_orgnization base_orgnization { get; set; }
    }
}
