//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_company
    {
        public int id { get; set; }
        public Nullable<int> prentid { get; set; }
        public string com_code { get; set; }
        public string com_name { get; set; }
        public string com_class { get; set; }
        public string com_desc { get; set; }
        public Nullable<int> com_type { get; set; }
        public Nullable<int> createdby_id { get; set; }
        public string createdby_name { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public string updatedby { get; set; }
        public Nullable<int> deleteflag { get; set; }
        public string com_chairman { get; set; }
        public string com_tel { get; set; }
        public string com_person { get; set; }
        public string FMonthly { get; set; }
        public Nullable<int> FMonthlyDay { get; set; }
        public string FAddress { get; set; }
    }
}
