//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_code
    {
        public int id { get; set; }
        public string category { get; set; }
        public string key { get; set; }
        public string value { get; set; }
        public string desc { get; set; }
        public Nullable<int> sort { get; set; }
        public string exttext1 { get; set; }
        public string exttext2 { get; set; }
        public string exttext3 { get; set; }
        public string exttext4 { get; set; }
        public Nullable<int> deleteflag { get; set; }
    }
}
