//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_orgnization
    {
        public base_orgnization()
        {
            this.base_account = new HashSet<base_account>();
            this.base_employee = new HashSet<base_employee>();
        }
    
        public int id { get; set; }
        public Nullable<int> org_parent_id { get; set; }
        public string cate_code { get; set; }
        public string code { get; set; }
        public string org_name { get; set; }
        public string org_node_imageurl { get; set; }
        public Nullable<int> org_sort { get; set; }
        public Nullable<int> org_type { get; set; }
        public Nullable<int> org_account_id { get; set; }
        public string org_account_name { get; set; }
        public string org_office_fax { get; set; }
        public string org_office_tel { get; set; }
        public string org_desc { get; set; }
        public string code_cn { get; set; }
        public Nullable<int> createdby_id { get; set; }
        public string createdby_name { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> deleteflag { get; set; }
        public Nullable<int> FCompanyId { get; set; }
        public Nullable<int> FFlag { get; set; }
    
        public virtual ICollection<base_account> base_account { get; set; }
        public virtual ICollection<base_employee> base_employee { get; set; }
    }
}
