//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_account
    {
        public int id { get; set; }
        public string account_name { get; set; }
        public string account_number { get; set; }
        public string account_password { get; set; }
        public Nullable<int> account_sort { get; set; }
        public Nullable<int> account_org_id { get; set; }
        public string account_role_id { get; set; }
        public string account_role_name { get; set; }
        public Nullable<int> account_role_indicator { get; set; }
        public Nullable<int> account_past_due { get; set; }
        public Nullable<int> account_ip_flag { get; set; }
        public string account_ip { get; set; }
        public string account_ip_addres { get; set; }
        public Nullable<int> account_mac_flag { get; set; }
        public string account_mac { get; set; }
        public Nullable<int> account_succee_count { get; set; }
        public Nullable<System.DateTime> account_last_date { get; set; }
        public Nullable<int> account_error_account { get; set; }
        public Nullable<int> account_flag { get; set; }
        public string account_sex { get; set; }
        public Nullable<int> account_post { get; set; }
        public Nullable<int> account_major { get; set; }
        public string account_mobile_phone { get; set; }
        public string account_qq { get; set; }
        public string account_email { get; set; }
        public Nullable<int> account_company_id { get; set; }
        public string account_company_name { get; set; }
        public string account_classes { get; set; }
        public string account_job { get; set; }
        public string code_cn { get; set; }
        public Nullable<int> createdby_id { get; set; }
        public string createdby_name { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> updatedby { get; set; }
        public Nullable<System.DateTime> updatedon { get; set; }
        public Nullable<int> deleteflag { get; set; }
        public Nullable<int> FCompanyId { get; set; }
        public Nullable<int> FFlag { get; set; }
    
        public virtual base_orgnization base_orgnization { get; set; }
    }
}
