//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_messagerie
    {
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> message_type { get; set; }
        public Nullable<int> sender_id { get; set; }
        public string sender_name { get; set; }
        public Nullable<System.DateTime> sendere_date { get; set; }
        public Nullable<int> receiver_id { get; set; }
        public string receiver_name { get; set; }
        public string reading_state { get; set; }
        public Nullable<System.DateTime> reading_date { get; set; }
        public int reading_count { get; set; }
        public string message_content { get; set; }
        public Nullable<int> deleteflag { get; set; }
        public string enclosure_code { get; set; }
        public Nullable<int> FCompanyId { get; set; }
        public Nullable<int> FFlag { get; set; }
    }
}
