//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_province
    {
        public int id { get; set; }
        public string codeid { get; set; }
        public Nullable<int> p_code { get; set; }
        public string city_name { get; set; }
        public string city_namescode { get; set; }
        public string city_namecode { get; set; }
    }
}
