//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_sequence
    {
        public string PREFIX { get; set; }
        public string SECTION { get; set; }
        public int FCompanyId { get; set; }
        public Nullable<int> VALUELEN { get; set; }
        public Nullable<int> MAXVALUE { get; set; }
        public Nullable<int> STEP { get; set; }
        public string SECTIONRULE { get; set; }
    }
}
