//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_configset
    {
        public int id { get; set; }
        public string name { get; set; }
        public string abbreviation { get; set; }
        public string keywords { get; set; }
        public string description { get; set; }
        public string icp { get; set; }
        public string cookieDomain { get; set; }
        public string siteID { get; set; }
        public string version { get; set; }
        public Nullable<int> allowReg { get; set; }
        public Nullable<int> checkReg { get; set; }
        public string logo { get; set; }
        public Nullable<int> createdby_id { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> deleteflag { get; set; }
    }
}
