//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class LHBottleDetectionDetails
    {
        public int FId { get; set; }
        public string KeyId { get; set; }
        public string FItemCode { get; set; }
        public Nullable<decimal> FPrice { get; set; }
        public Nullable<decimal> FQty { get; set; }
        public Nullable<decimal> FAmount { get; set; }
        public string FBottle { get; set; }
        public Nullable<int> FBottleQty { get; set; }
        public Nullable<int> FBottleOweQty { get; set; }
        public Nullable<int> FCompanyId { get; set; }
        public Nullable<int> FCateId { get; set; }
        public string FMemo { get; set; }
        public Nullable<int> FRecycleQty { get; set; }
        public string FAssociatedNo { get; set; }
        public Nullable<decimal> FCostPrice { get; set; }
        public Nullable<decimal> FBalance { get; set; }
        public string FBSpec { get; set; }
    }
}
