//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class LHContract
    {
        public int FId { get; set; }
        public string FOrderCode { get; set; }
        public string FContractCode { get; set; }
        public Nullable<System.DateTime> FContractDate { get; set; }
        public string FContractName { get; set; }
        public string FCtroler { get; set; }
        public string FAccType { get; set; }
        public string FBillType { get; set; }
        public Nullable<System.DateTime> FBeginDate { get; set; }
        public Nullable<System.DateTime> FEndDate { get; set; }
        public string FCustomer { get; set; }
        public string FConacter { get; set; }
        public string FTel { get; set; }
        public string FContext { get; set; }
        public Nullable<System.DateTime> FCreatedon { get; set; }
        public string FCreatedby { get; set; }
        public Nullable<System.DateTime> FUpdateon { get; set; }
        public string FUpdateby { get; set; }
        public Nullable<int> FDeleteflag { get; set; }
        public Nullable<int> FCompanyId { get; set; }
    }
}
