//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class LHCustomer
    {
        public string FCode { get; set; }
        public int FCompanyId { get; set; }
        public string FName { get; set; }
        public string FAddress { get; set; }
        public string FLinkman { get; set; }
        public string FPhome { get; set; }
        public string FMoile { get; set; }
        public string FMemo { get; set; }
        public Nullable<int> FIsPrint { get; set; }
        public Nullable<int> FTipsDay { get; set; }
        public Nullable<decimal> FFreight { get; set; }
        public Nullable<decimal> FCredit { get; set; }
        public string FSpell { get; set; }
        public Nullable<int> FFlag { get; set; }
        public string FSalesman { get; set; }
        public string FDistric { get; set; }
        public string FPaymentMethod { get; set; }
        public string FCateId { get; set; }
        public string FSubCateId { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public Nullable<int> FIsAllot { get; set; }
        public Nullable<int> FIsInvoice { get; set; }
        public Nullable<int> FIsKickback { get; set; }
        public Nullable<System.DateTime> FLastTime { get; set; }
        public string FGroupNo { get; set; }
        public string FGroupNoFlag { get; set; }
        public string FRebateFlag { get; set; }
        public string FPushFlag { get; set; }
        public string FMonthly { get; set; }
        public Nullable<int> FMonthlyDay { get; set; }
        public string FSubCateName { get; set; }
        public Nullable<int> FLevel { get; set; }
        public Nullable<int> FPrintPrice { get; set; }
        public Nullable<decimal> FCreLine { get; set; }
        public string FARMoney { get; set; }
        public Nullable<decimal> FFrequency { get; set; }
        public string FProvince { get; set; }
        public string FCity { get; set; }
        public string FCounty { get; set; }
        public string FZipCode { get; set; }
        public Nullable<int> FProvinceId { get; set; }
        public Nullable<int> FCityId { get; set; }
        public Nullable<int> FCountyId { get; set; }
        public Nullable<int> FCreditDays { get; set; }
        public Nullable<decimal> FCreditValue { get; set; }
        public string FCreditFlag { get; set; }
        public string FPassword { get; set; }
        public string FCoordinate { get; set; }
    }
}
