//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class LHCustomerPrice
    {
        public int FId { get; set; }
        public string FCode { get; set; }
        public string FItemCode { get; set; }
        public Nullable<decimal> FPrice { get; set; }
        public Nullable<int> FCompanyId { get; set; }
        public string FCreateBy { get; set; }
        public Nullable<System.DateTime> FCreateDate { get; set; }
        public string FUpdateBy { get; set; }
        public Nullable<System.DateTime> FUpdateDate { get; set; }
        public string FAuditor { get; set; }
        public Nullable<System.DateTime> FAuditDate { get; set; }
        public Nullable<int> FFlag { get; set; }
        public string FMemo { get; set; }
        public Nullable<System.DateTime> FBeginDate { get; set; }
        public Nullable<System.DateTime> FEndDate { get; set; }
    }
}
