//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class LHDevice
    {
        public string FCode { get; set; }
        public int FCompanyId { get; set; }
        public string FName { get; set; }
        public string FSpell { get; set; }
        public Nullable<decimal> FQty { get; set; }
        public string FUnit { get; set; }
        public string FCateId { get; set; }
        public string FSubCateId { get; set; }
        public string FParms { get; set; }
        public string FUser { get; set; }
        public string FAddress { get; set; }
        public Nullable<System.DateTime> FPurchaseDate { get; set; }
        public Nullable<System.DateTime> FInstallDate { get; set; }
        public string FInspectionCycle { get; set; }
        public string FInstallByName { get; set; }
        public string FMemo { get; set; }
        public Nullable<int> FStatus { get; set; }
        public Nullable<int> FDays { get; set; }
        public string FSpec { get; set; }
        public Nullable<int> FFlag { get; set; }
    }
}
