//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class LHDispatchCenter
    {
        public string KeyId { get; set; }
        public int FCompanyId { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public Nullable<System.DateTime> FBeginDate { get; set; }
        public string FVehicleNum { get; set; }
        public string FTrailerPlate { get; set; }
        public string FDriver { get; set; }
        public string FSupercargo { get; set; }
        public string CreateBy { get; set; }
        public Nullable<int> FFlag { get; set; }
        public Nullable<System.DateTime> FEndDate { get; set; }
        public Nullable<decimal> FMileage { get; set; }
        public Nullable<System.DateTime> FFuelingDate { get; set; }
        public Nullable<decimal> FPrice { get; set; }
        public Nullable<decimal> FQty { get; set; }
        public string FCate { get; set; }
        public Nullable<decimal> FAccount { get; set; }
        public string Memo { get; set; }
        public Nullable<decimal> FOtherExpenses { get; set; }
        public string FBeginTime { get; set; }
        public string FEndTime { get; set; }
        public string FLogistics { get; set; }
        public string FLogisticsCode { get; set; }
        public string FFrom { get; set; }
        public string FTo { get; set; }
        public string FVehicleType { get; set; }
        public Nullable<decimal> FTonnage { get; set; }
        public string FOperationCertificateNo { get; set; }
        public string FItem { get; set; }
        public Nullable<int> FBottleQty { get; set; }
        public Nullable<int> FNumber { get; set; }
        public Nullable<decimal> FActual { get; set; }
        public string FUnit { get; set; }
        public Nullable<int> FIsIn { get; set; }
        public string FAuditor { get; set; }
        public Nullable<int> FAuditFlag { get; set; }
        public string FDeliveryMethod { get; set; }
        public string FFullloadFlag { get; set; }
        public Nullable<decimal> FFullloadRatio { get; set; }
        public string FFullloadPerson { get; set; }
    }
}
