//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class LHDispatch
    {
        public string KeyId { get; set; }
        public int FCompanyId { get; set; }
        public Nullable<int> FWorkQty { get; set; }
        public Nullable<int> FStopQty { get; set; }
        public Nullable<int> FRepairQty { get; set; }
        public Nullable<int> FAccidentQty { get; set; }
        public Nullable<int> FOtherQty { get; set; }
        public Nullable<int> FIDepartureTime { get; set; }
        public Nullable<decimal> FIRange { get; set; }
        public Nullable<decimal> FIQty { get; set; }
        public Nullable<int> FODepartureTime { get; set; }
        public Nullable<decimal> FORange { get; set; }
        public Nullable<decimal> FOQty { get; set; }
        public Nullable<decimal> FHeavyTruckQty { get; set; }
        public Nullable<decimal> FSumQty { get; set; }
        public Nullable<decimal> FTransport { get; set; }
        public Nullable<decimal> FTurnover { get; set; }
        public Nullable<int> FDeleteFlag { get; set; }
        public Nullable<int> FFlag { get; set; }
        public Nullable<int> FType { get; set; }
        public Nullable<int> FProgress { get; set; }
        public Nullable<int> FStatus { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public string FLogistics { get; set; }
        public string FDispatcher { get; set; }
        public string FMemo { get; set; }
        public string FLogisticsName { get; set; }
    }
}
