//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class LHFKOrderBanks
    {
        public int FId { get; set; }
        public string KeyId { get; set; }
        public string FCode { get; set; }
        public string FName { get; set; }
        public Nullable<decimal> FAmt { get; set; }
        public string FCardNo { get; set; }
        public string FBankNo { get; set; }
        public string FBillNo { get; set; }
        public Nullable<System.DateTime> FExpireDate { get; set; }
        public string FMemo { get; set; }
        public Nullable<int> FCompanyId { get; set; }
        public Nullable<decimal> FDiscountAmount { get; set; }
    }
}
