//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class LHInitStockQty
    {
        public int FId { get; set; }
        public string FDate { get; set; }
        public string FDistributionPoint { get; set; }
        public string FCode { get; set; }
        public Nullable<int> FCompanyId { get; set; }
        public string FCateId { get; set; }
        public Nullable<int> FInitQty { get; set; }
        public Nullable<decimal> FInitQtyKg { get; set; }
    }
}
