//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class LHItems
    {
        public string FCode { get; set; }
        public int FCompanyId { get; set; }
        public string FName { get; set; }
        public string FSpell { get; set; }
        public string FGroupNum { get; set; }
        public string FSpec { get; set; }
        public string FUnit { get; set; }
        public string FCateId { get; set; }
        public string FSubCateId { get; set; }
        public Nullable<decimal> FPurchasePrice { get; set; }
        public Nullable<decimal> FSalesPrice { get; set; }
        public string FMemo { get; set; }
        public Nullable<int> FFlag { get; set; }
        public Nullable<decimal> FCostPrice { get; set; }
        public string FInventory { get; set; }
        public string FIsLiquid { get; set; }
        public string FSubCateName { get; set; }
        public Nullable<decimal> FPieceWork1 { get; set; }
        public Nullable<decimal> FPieceWork2 { get; set; }
        public Nullable<decimal> FPieceWork3 { get; set; }
        public Nullable<decimal> FPieceWork4 { get; set; }
        public Nullable<decimal> FPieceWork5 { get; set; }
        public Nullable<decimal> FPieceWork6 { get; set; }
        public Nullable<decimal> FQty { get; set; }
        public string FINum { get; set; }
        public string FIInvNum { get; set; }
        public Nullable<int> FITaxRate { get; set; }
        public Nullable<decimal> FPress { get; set; }
        public Nullable<decimal> FNetWeight { get; set; }
        public Nullable<int> FScm { get; set; }
        public Nullable<decimal> FPurity { get; set; }
        public Nullable<decimal> FCpn { get; set; }
        public Nullable<decimal> FVolume { get; set; }
        public Nullable<decimal> FMakePay { get; set; }
        public Nullable<int> FBottleQty { get; set; }
        public string FRack { get; set; }
        public string cinvdefine1 { get; set; }
    }
}
