//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class LHLeaseReturn
    {
        public string KeyId { get; set; }
        public int FCompanyId { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public string FCode { get; set; }
        public string FName { get; set; }
        public string FAddress { get; set; }
        public string FPhone { get; set; }
        public string FLinkman { get; set; }
        public string FVehicleNum { get; set; }
        public string FDeliveryMethod { get; set; }
        public string FDriver { get; set; }
        public string FSupercargo { get; set; }
        public string FMemo { get; set; }
        public Nullable<int> FFlag { get; set; }
        public Nullable<int> FType { get; set; }
        public string FShipper { get; set; }
        public Nullable<int> FProgress { get; set; }
        public Nullable<int> FStatus { get; set; }
        public Nullable<int> FIsPrint { get; set; }
        public string FAuditor { get; set; }
        public Nullable<int> FAuditFlag { get; set; }
        public Nullable<int> FDeleteFlag { get; set; }
        public string FClass { get; set; }
        public string FSubjectCodeIn { get; set; }
        public string FSubjectNameIn { get; set; }
        public Nullable<decimal> FPaymentRentals { get; set; }
        public string FDispatchNum { get; set; }
        public string FSubjectCodeOut { get; set; }
        public string FSubjectNameOut { get; set; }
        public Nullable<decimal> FDepositSecurity { get; set; }
        public Nullable<decimal> FDiscountAmount { get; set; }
        public string FSKNum { get; set; }
        public string FFKNum { get; set; }
        public string FCate { get; set; }
        public Nullable<decimal> FFreight { get; set; }
        public Nullable<System.DateTime> FEndDate { get; set; }
    }
}
