//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class LHLiquidRefuel
    {
        public int FId { get; set; }
        public string KeyId { get; set; }
        public Nullable<int> FCompanyId { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public string FAssociatedNo { get; set; }
        public string FItemCode { get; set; }
        public Nullable<decimal> FQty { get; set; }
        public Nullable<decimal> FPrice { get; set; }
        public Nullable<decimal> FAmount { get; set; }
        public string FSource { get; set; }
        public string FVehicleNum { get; set; }
        public string FBeginAddress { get; set; }
        public string FEndAddress { get; set; }
        public Nullable<decimal> FBeginMileage { get; set; }
        public Nullable<decimal> FEndMileage { get; set; }
        public Nullable<decimal> FMileage { get; set; }
        public Nullable<decimal> FOtherAmount { get; set; }
        public string CreateBy { get; set; }
        public Nullable<int> FFlag { get; set; }
    }
}
