//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class LHLiquidPlan
    {
        public string KeyId { get; set; }
        public int FCompanyId { get; set; }
        public string CreateBy { get; set; }
        public string FBill { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public string FItemCode { get; set; }
        public string FItemName { get; set; }
        public Nullable<int> FType { get; set; }
        public string FVehicleNum { get; set; }
        public string FTrailerNum { get; set; }
        public string FDriver { get; set; }
        public string FSupercargo { get; set; }
        public Nullable<decimal> FStartMileage { get; set; }
        public Nullable<decimal> FQty { get; set; }
        public Nullable<decimal> FPrice { get; set; }
        public Nullable<decimal> FAmount { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public string FMemo { get; set; }
        public Nullable<System.DateTime> FDepartureTime { get; set; }
        public Nullable<System.DateTime> FEndTime { get; set; }
        public Nullable<int> FFlag { get; set; }
        public Nullable<int> FStatus { get; set; }
        public string FSupplierCode { get; set; }
        public string FSupplierName { get; set; }
        public Nullable<decimal> FPurchasedPrice { get; set; }
        public Nullable<decimal> FPurchasedPQty { get; set; }
        public Nullable<decimal> FPurchasedQty { get; set; }
        public Nullable<decimal> FPurchasedAmt { get; set; }
        public string FPurchasedDate { get; set; }
        public string FCode1 { get; set; }
        public string FCode2 { get; set; }
        public string FCode3 { get; set; }
        public string FCode4 { get; set; }
        public string FName1 { get; set; }
        public string FName2 { get; set; }
        public string FName3 { get; set; }
        public string FName4 { get; set; }
        public Nullable<System.DateTime> FDate1 { get; set; }
        public Nullable<System.DateTime> FDate2 { get; set; }
        public Nullable<System.DateTime> FDate3 { get; set; }
        public Nullable<System.DateTime> FDate4 { get; set; }
        public Nullable<decimal> FPrice1 { get; set; }
        public Nullable<decimal> FPrice2 { get; set; }
        public Nullable<decimal> FPrice3 { get; set; }
        public Nullable<decimal> FPrice4 { get; set; }
        public Nullable<decimal> FQty1 { get; set; }
        public Nullable<decimal> FQty2 { get; set; }
        public Nullable<decimal> FQty3 { get; set; }
        public Nullable<decimal> FQty4 { get; set; }
        public string FAddress1 { get; set; }
        public string FAddress2 { get; set; }
        public string FAddress3 { get; set; }
        public string FAddress4 { get; set; }
        public string FPhone1 { get; set; }
        public string FPhone2 { get; set; }
        public string FPhone3 { get; set; }
        public string FPhone4 { get; set; }
        public string FLinkman1 { get; set; }
        public string FLinkman2 { get; set; }
        public string FLinkman3 { get; set; }
        public string FLinkman4 { get; set; }
        public Nullable<decimal> FMarginEnd { get; set; }
        public Nullable<decimal> FMargin { get; set; }
        public Nullable<int> FDeleteFlag { get; set; }
        public Nullable<decimal> FPQty1 { get; set; }
        public Nullable<decimal> FPQty2 { get; set; }
        public Nullable<decimal> FPQty3 { get; set; }
        public Nullable<decimal> FPQty4 { get; set; }
        public Nullable<decimal> FGross { get; set; }
        public Nullable<decimal> FGross1 { get; set; }
        public Nullable<decimal> FGross2 { get; set; }
        public Nullable<decimal> FGross3 { get; set; }
        public Nullable<decimal> FGross4 { get; set; }
        public Nullable<decimal> FPacked { get; set; }
        public Nullable<decimal> FPacked1 { get; set; }
        public Nullable<decimal> FPacked2 { get; set; }
        public Nullable<decimal> FPacked3 { get; set; }
        public Nullable<decimal> FPacked4 { get; set; }
        public string KeyId1 { get; set; }
        public string KeyId2 { get; set; }
        public string KeyId3 { get; set; }
        public string KeyId4 { get; set; }
        public string KeyId5 { get; set; }
        public string FTime1 { get; set; }
        public string FTime2 { get; set; }
        public string FTime3 { get; set; }
        public string FTime4 { get; set; }
        public Nullable<decimal> FAmt { get; set; }
        public Nullable<decimal> FAmt1 { get; set; }
        public Nullable<decimal> FAmt2 { get; set; }
        public Nullable<decimal> FAmt3 { get; set; }
        public Nullable<decimal> FAmt4 { get; set; }
        public Nullable<decimal> FMileage { get; set; }
        public string FT6Warehouse { get; set; }
        public string FDistributionPoint { get; set; }
    }
}
