//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class LHLiquidTo
    {
        public string XKeyId { get; set; }
        public int XCompanyId { get; set; }
        public Nullable<decimal> XMargin { get; set; }
        public Nullable<decimal> XMarginEnd { get; set; }
        public Nullable<decimal> XQty { get; set; }
        public string XVehicleNum { get; set; }
        public string XTo { get; set; }
        public string XBill { get; set; }
        public string XMemo { get; set; }
        public string XKeyId1 { get; set; }
        public string XKeyId2 { get; set; }
        public Nullable<System.DateTime> XFDate { get; set; }
        public string XCreateBy { get; set; }
    }
}
