//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class LHOilCardDetails
    {
        public int FId { get; set; }
        public string FCode { get; set; }
        public Nullable<decimal> FAmount { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public string FCreateBy { get; set; }
        public string FOperator { get; set; }
        public string FMemo { get; set; }
        public string FType { get; set; }
        public Nullable<decimal> FQty { get; set; }
        public Nullable<decimal> FPrice { get; set; }
        public Nullable<decimal> FAmt1 { get; set; }
        public Nullable<decimal> FAmt2 { get; set; }
    }
}
