//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class LHOilCard
    {
        public int FId { get; set; }
        public string FCode { get; set; }
        public Nullable<decimal> FAmount { get; set; }
        public string FMemo { get; set; }
        public Nullable<int> FFlag { get; set; }
        public Nullable<int> FDeleteFlag { get; set; }
        public Nullable<int> FCompanyId { get; set; }
        public Nullable<int> FISMain { get; set; }
        public string FMainNum { get; set; }
        public string FVehicle { get; set; }
    }
}
