//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class LHSafeCheck
    {
        public int FId { get; set; }
        public string FOrderNo { get; set; }
        public Nullable<System.DateTime> FCheckDate { get; set; }
        public string FTypeNum { get; set; }
        public Nullable<System.DateTime> FReformDate { get; set; }
        public string FContext { get; set; }
        public string FReason { get; set; }
        public string FMarkContext { get; set; }
        public Nullable<decimal> FFunds { get; set; }
        public string FDept { get; set; }
        public string FPerson { get; set; }
        public Nullable<System.DateTime> Createon { get; set; }
        public string Createby { get; set; }
        public Nullable<System.DateTime> Updateon { get; set; }
        public string Updateby { get; set; }
        public Nullable<int> FDeleteFlag { get; set; }
    }
}
