//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class LHSalaryDriver
    {
        public int FId { get; set; }
        public string KeyId { get; set; }
        public string FLogistics { get; set; }
        public string FVehicleNum { get; set; }
        public string FDriver { get; set; }
        public string FFrom { get; set; }
        public string FTo { get; set; }
        public string FSupercargo { get; set; }
        public Nullable<System.DateTime> FBeginDate { get; set; }
        public Nullable<System.DateTime> FEndDate { get; set; }
        public Nullable<decimal> FDiffDayAmount { get; set; }
        public Nullable<decimal> FDriverMileageAmt { get; set; }
        public Nullable<decimal> FSupercargoMileageAmt { get; set; }
        public Nullable<decimal> FMileage { get; set; }
        public string FAuditFlag { get; set; }
        public Nullable<decimal> FDiffDay { get; set; }
        public Nullable<decimal> FDriverYPrice { get; set; }
        public Nullable<decimal> FDriverYAmount { get; set; }
        public Nullable<decimal> FDriverYQty { get; set; }
        public Nullable<decimal> FDriverPrice { get; set; }
        public Nullable<decimal> FDriverAmount { get; set; }
        public Nullable<decimal> FDriverQty { get; set; }
        public Nullable<decimal> FDriverJPrice { get; set; }
        public Nullable<decimal> FDriverJAmount { get; set; }
        public Nullable<decimal> FDriverJQty { get; set; }
        public Nullable<decimal> FDriverTPrice { get; set; }
        public Nullable<decimal> FDriverTAmount { get; set; }
        public Nullable<decimal> TaskQty { get; set; }
        public Nullable<decimal> FSupercargoYPrice { get; set; }
        public Nullable<decimal> FSupercargoYAmount { get; set; }
        public Nullable<decimal> FSupercargoYQty { get; set; }
        public Nullable<decimal> FSupercargoPrice { get; set; }
        public Nullable<decimal> FSupercargoAmount { get; set; }
        public Nullable<decimal> FSupercargoQty { get; set; }
        public Nullable<decimal> FSupercargoJPrice { get; set; }
        public Nullable<decimal> FSupercargoJAmount { get; set; }
        public Nullable<decimal> FSupercargoJQty { get; set; }
        public Nullable<decimal> FSupercargoTPrice { get; set; }
        public Nullable<decimal> FSupercargoTAmount { get; set; }
        public string FMemo { get; set; }
    }
}
