//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class LHStockOutDispatch
    {
        public int FId { get; set; }
        public string KeyId { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public string DeliveryMethod { get; set; }
        public string FDistributionPoint { get; set; }
        public string FMemo { get; set; }
        public int FCompanyid { get; set; }
        public int FFlag { get; set; }
        public int FState { get; set; }
    }
}
