//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class LHStockOut_trigger
    {
        public string KeyId { get; set; }
        public int FCompanyId { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public string FCode { get; set; }
        public string FName { get; set; }
        public string FAddress { get; set; }
        public string FPhone { get; set; }
        public string FLinkman { get; set; }
        public string FVehicleNum { get; set; }
        public string FDeliveryMethod { get; set; }
        public string FDriver { get; set; }
        public string FSupercargo { get; set; }
        public string FSalesman { get; set; }
        public string FMemo { get; set; }
        public Nullable<int> FFlag { get; set; }
        public string FUpdateBy { get; set; }
        public Nullable<System.DateTime> FUpdateDate { get; set; }
        public Nullable<int> FType { get; set; }
        public Nullable<decimal> FFreight { get; set; }
        public Nullable<decimal> FAmount { get; set; }
        public Nullable<decimal> FAmt { get; set; }
        public Nullable<decimal> FDiscountAmount { get; set; }
        public string FShipper { get; set; }
        public Nullable<int> FProgress { get; set; }
        public Nullable<int> FStatus { get; set; }
        public Nullable<int> FIsPrint { get; set; }
        public string FReconciliation { get; set; }
        public string FBarcode { get; set; }
        public string FAuditor { get; set; }
        public Nullable<int> FAuditFlag { get; set; }
        public string FArea { get; set; }
        public string FLogisticsNumber { get; set; }
        public Nullable<int> FDeleteFlag { get; set; }
        public string FAllotWay { get; set; }
        public string FCate { get; set; }
        public string FSubjectCode { get; set; }
        public string FSubjectName { get; set; }
        public string FAssociatedNo { get; set; }
        public string FBatchNumber { get; set; }
        public string FProducer { get; set; }
        public string FSurveyor { get; set; }
        public string FDispatchNum { get; set; }
        public string FSKNum { get; set; }
        public string FClass { get; set; }
        public string FT6Warehouse { get; set; }
        public string FT6SaleType { get; set; }
        public string FT6SaleTypeNum { get; set; }
        public string FT6PurchaseType { get; set; }
        public string FT6PurchaseTypeNum { get; set; }
        public string FT6ReceiveSendType { get; set; }
        public string FT6ReceiveSendTypeNum { get; set; }
        public string FT6Department { get; set; }
        public string FT6DepartmentNum { get; set; }
        public string FT6SalesmanNum { get; set; }
        public Nullable<decimal> FT6TaxRate { get; set; }
        public string FT6Currency { get; set; }
        public Nullable<decimal> FT6ExchangeRate { get; set; }
        public string FT6Status { get; set; }
        public string FDistributionPoint { get; set; }
        public Nullable<int> FOrgId { get; set; }
        public string FOrgName { get; set; }
        public string FT6BillStatus { get; set; }
        public string FT6PaymentStatus { get; set; }
        public string FPoint { get; set; }
        public string FGroup { get; set; }
        public string FSendee { get; set; }
        public string FSendeeFlag { get; set; }
        public Nullable<int> FinancialFlag { get; set; }
        public string FinancialPerson { get; set; }
        public Nullable<System.DateTime> FinancialData { get; set; }
        public Nullable<int> FSendReceiveFlag { get; set; }
        public string FSendReceivePerson { get; set; }
        public string FReceiver { get; set; }
        public Nullable<System.DateTime> FT6Date { get; set; }
        public Nullable<System.DateTime> FTime1 { get; set; }
        public Nullable<System.DateTime> FTime2 { get; set; }
        public Nullable<System.DateTime> FTime3 { get; set; }
        public Nullable<System.DateTime> FTime4 { get; set; }
    }
}
