//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class LHStockInLiquid
    {
        public int id { get; set; }
        public string keyid { get; set; }
        public int Rowid { get; set; }
        public string companyid { get; set; }
        public string FDevice { get; set; }
        public Nullable<decimal> FDeviceValue { get; set; }
        public decimal Temperature { get; set; }
        public decimal Bar { get; set; }
        public decimal InTemperature { get; set; }
        public decimal InBar { get; set; }
    }
}
