//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class LHTubePrice
    {
        public int FId { get; set; }
        public string FBill { get; set; }
        public string FCode { get; set; }
        public string FItemCode { get; set; }
        public string FMemo { get; set; }
        public string FFormula1 { get; set; }
        public string FFormula2 { get; set; }
        public string FFormula { get; set; }
    }
}
