//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class LHVehicleCard
    {
        public int FId { get; set; }
        public string FNum { get; set; }
        public Nullable<System.DateTime> FCertificateDate { get; set; }
        public Nullable<decimal> FCertificateMoney { get; set; }
        public Nullable<System.DateTime> FDrivingDate { get; set; }
        public Nullable<decimal> FDrivingMoney { get; set; }
        public Nullable<System.DateTime> FDeadlineDate { get; set; }
        public Nullable<System.DateTime> FCommercialDate { get; set; }
        public Nullable<decimal> FCommercialMoney { get; set; }
        public Nullable<System.DateTime> FDangerousDate { get; set; }
        public Nullable<decimal> FDangerousMoney { get; set; }
        public Nullable<System.DateTime> FTankDate { get; set; }
        public Nullable<System.DateTime> FRegistrationDate { get; set; }
        public Nullable<decimal> FTankMoney { get; set; }
        public Nullable<decimal> FRegistrationMoney { get; set; }
        public Nullable<decimal> FDeadlineMoney { get; set; }
        public Nullable<System.DateTime> FTwostageDate { get; set; }
        public Nullable<decimal> FTwostageMoney { get; set; }
        public Nullable<System.DateTime> FCreatedon { get; set; }
        public string Createdby { get; set; }
        public Nullable<int> FDeleteFlag { get; set; }
        public string FContext { get; set; }
    }
}
