//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class LHVehicleEtc
    {
        public int FId { get; set; }
        public string FVehicleNum { get; set; }
        public Nullable<System.DateTime> FDateI { get; set; }
        public string FPortalEntry { get; set; }
        public Nullable<System.DateTime> FDateO { get; set; }
        public string FPortalExit { get; set; }
        public string FProvince { get; set; }
        public string FNature { get; set; }
        public Nullable<decimal> FExpenditure { get; set; }
        public Nullable<decimal> FDeposit { get; set; }
        public Nullable<decimal> FRebate { get; set; }
        public Nullable<int> FFlag { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
    }
}
