//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class LHVehicle
    {
        public int FId { get; set; }
        public string FNum { get; set; }
        public string FColor { get; set; }
        public Nullable<System.DateTime> FRegData { get; set; }
        public string FPerson { get; set; }
        public string FLicenseNum { get; set; }
        public string FMethod { get; set; }
        public Nullable<int> FFlag { get; set; }
        public Nullable<int> FCompanyId { get; set; }
        public string FEngineNo { get; set; }
        public string FVIN { get; set; }
        public Nullable<System.DateTime> FDated { get; set; }
        public Nullable<System.DateTime> FLicenseDate { get; set; }
        public string FMemo { get; set; }
        public string FTypeNo { get; set; }
        public string FBrand { get; set; }
        public string FTypeNum { get; set; }
        public string FTonner { get; set; }
        public string FQuality { get; set; }
        public string FLx { get; set; }
        public Nullable<decimal> FWear { get; set; }
        public Nullable<System.DateTime> FFactoryDate { get; set; }
        public string FEngineType { get; set; }
        public string Fuel { get; set; }
        public string FDesplaceMent { get; set; }
        public string FPower { get; set; }
        public string FReginNo { get; set; }
        public string FRegionCompany { get; set; }
        public string FOperateNum { get; set; }
        public string FDrvierNum { get; set; }
        public Nullable<System.DateTime> FCertificateDate { get; set; }
        public Nullable<decimal> FCertificateMoney { get; set; }
        public Nullable<System.DateTime> FDrivingDate { get; set; }
        public Nullable<decimal> FDrivingMoney { get; set; }
        public Nullable<System.DateTime> FDeadlineDate { get; set; }
        public Nullable<System.DateTime> FCommercialDate { get; set; }
        public Nullable<decimal> FCommercialMoney { get; set; }
        public Nullable<System.DateTime> FDangerousDate { get; set; }
        public Nullable<decimal> FDangerousMoney { get; set; }
        public Nullable<System.DateTime> FTankDate { get; set; }
        public Nullable<System.DateTime> FRegistrationDate { get; set; }
        public Nullable<decimal> TankMoney { get; set; }
        public Nullable<decimal> FRegistrationMoney { get; set; }
        public Nullable<decimal> FDeadlineMoney { get; set; }
        public Nullable<System.DateTime> FTwostageDate { get; set; }
        public Nullable<decimal> FTwostageMoney { get; set; }
        public string FCompanyName { get; set; }
        public Nullable<decimal> FMargin { get; set; }
        public Nullable<decimal> FMeteredPrice { get; set; }
        public Nullable<decimal> FWaterSpace { get; set; }
        public string FRunStatus { get; set; }
        public string FLogistics { get; set; }
        public string FISMain { get; set; }
        public Nullable<int> FValFlag { get; set; }
    }
}
