//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class LHWarehouse
    {
        public string FCode { get; set; }
        public int FCompanyId { get; set; }
        public string FName { get; set; }
        public string FSpell { get; set; }
        public string FLinkman { get; set; }
        public string FAddress { get; set; }
        public string FPhome { get; set; }
        public string FMemo { get; set; }
        public Nullable<int> FFlag { get; set; }
        public string FItemType { get; set; }
        public string FINum { get; set; }
    }
}
