//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CustomerItemPrice
    {
        public Nullable<long> rownum { get; set; }
        public string FCode { get; set; }
        public string customername { get; set; }
        public string FAddress { get; set; }
        public string FItemCode { get; set; }
        public Nullable<decimal> FPrice { get; set; }
        public string itemname { get; set; }
        public string FSpec { get; set; }
    }
}
