//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ProducePlacePrice
    {
        public string rownum { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public string FINum { get; set; }
        public string FItemCode { get; set; }
        public string FName { get; set; }
        public string FSpell { get; set; }
        public Nullable<decimal> FPrice { get; set; }
        public string FUnit { get; set; }
        public Nullable<decimal> FQty { get; set; }
        public string FDistributionPoint { get; set; }
    }
}
