//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class vm_BankFlow
    {
        public string KeyId { get; set; }
        public int FCompanyId { get; set; }
        public string FCode { get; set; }
        public string FCate { get; set; }
        public string FName { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public string FMemo { get; set; }
        public string AFAbstract { get; set; }
        public Nullable<int> FType { get; set; }
        public int FId { get; set; }
        public string FItemCode { get; set; }
        public string FItemName { get; set; }
        public Nullable<decimal> FAmtIn { get; set; }
        public Nullable<decimal> FAmtOut { get; set; }
        public string BFAbstract { get; set; }
        public string Flag { get; set; }
    }
}
