//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class vm_contractList
    {
        public int FId { get; set; }
        public string FOrderCode { get; set; }
        public string FProductID { get; set; }
        public Nullable<decimal> FPrice { get; set; }
        public Nullable<int> Fstate { get; set; }
        public string FCreatedby { get; set; }
        public Nullable<System.DateTime> FCreatedon { get; set; }
        public string FUpdatedby { get; set; }
        public Nullable<System.DateTime> FUpdatedon { get; set; }
        public string ProductName { get; set; }
        public string FSpec { get; set; }
        public string FUnit { get; set; }
        public string statename { get; set; }
    }
}
