//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class vm_DispatchTask
    {
        public string KeyId { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public string FCode { get; set; }
        public string FName { get; set; }
        public string FLinkman { get; set; }
        public string FPhone { get; set; }
        public string FVehicleNum { get; set; }
        public string FDriver { get; set; }
        public string FSupercargo { get; set; }
        public string FMemo { get; set; }
        public Nullable<decimal> FQty { get; set; }
        public int FCompanyId { get; set; }
        public string FDispatchNum { get; set; }
        public string FDistric { get; set; }
        public string FSubCateName { get; set; }
        public string FStatus { get; set; }
        public string FOutFlag { get; set; }
        public Nullable<int> FType { get; set; }
        public Nullable<int> FOrgId { get; set; }
        public string FOrgName { get; set; }
        public string FAddress { get; set; }
        public string FDistributionPoint { get; set; }
        public string fbill { get; set; }
    }
}
