//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class vm_LeaseBottleAR
    {
        public string FCode { get; set; }
        public int FId { get; set; }
        public string FBottle { get; set; }
        public Nullable<int> FCompanyId { get; set; }
        public string FName { get; set; }
        public string FSpec { get; set; }
        public string FUnit { get; set; }
        public Nullable<int> FBottleQty { get; set; }
        public Nullable<decimal> FPrice { get; set; }
        public Nullable<decimal> FRentDay { get; set; }
        public int FReturnQty { get; set; }
        public Nullable<decimal> FAmount { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public Nullable<int> days { get; set; }
        public Nullable<int> ARBottleQty { get; set; }
        public Nullable<decimal> ARRentals { get; set; }
        public Nullable<decimal> FDepositSecurity { get; set; }
    }
}
