//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class vm_LiquidPlanList
    {
        public string KeyId { get; set; }
        public int FCompanyId { get; set; }
        public string CreateBy { get; set; }
        public string FBill { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public string FItemCode { get; set; }
        public string FItemName { get; set; }
        public string FVehicleNum { get; set; }
        public string FTrailerNum { get; set; }
        public string FDriver { get; set; }
        public string FSupercargo { get; set; }
        public Nullable<decimal> FStartMileage { get; set; }
        public Nullable<decimal> FQty { get; set; }
        public Nullable<decimal> FPrice { get; set; }
        public Nullable<decimal> FAmount { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public string FMemo { get; set; }
        public Nullable<System.DateTime> FDepartureTime { get; set; }
        public Nullable<int> FStatus { get; set; }
        public string FSupplierCode { get; set; }
        public string FSupplierName { get; set; }
        public Nullable<decimal> FPurchasedPrice { get; set; }
        public Nullable<decimal> FPurchasedPQty { get; set; }
        public Nullable<decimal> FPurchasedQty { get; set; }
        public string FCode1 { get; set; }
        public string FCode2 { get; set; }
        public string FCode3 { get; set; }
        public string FCode4 { get; set; }
        public string FName1 { get; set; }
        public string FName2 { get; set; }
        public string FName3 { get; set; }
        public string FName4 { get; set; }
        public Nullable<decimal> FPrice1 { get; set; }
        public Nullable<decimal> FPrice2 { get; set; }
        public Nullable<decimal> FPrice3 { get; set; }
        public Nullable<decimal> FPrice4 { get; set; }
        public Nullable<decimal> FQty1 { get; set; }
        public Nullable<decimal> FQty2 { get; set; }
        public Nullable<decimal> FQty3 { get; set; }
        public Nullable<decimal> FQty4 { get; set; }
        public Nullable<decimal> FMarginEnd { get; set; }
        public Nullable<decimal> FMargin { get; set; }
        public Nullable<decimal> FPQty1 { get; set; }
        public Nullable<decimal> FPQty2 { get; set; }
        public Nullable<decimal> FPQty3 { get; set; }
        public Nullable<decimal> FPQty4 { get; set; }
        public Nullable<decimal> FGross { get; set; }
        public Nullable<decimal> FAmt { get; set; }
        public Nullable<decimal> FAmt1 { get; set; }
        public Nullable<decimal> FAmt2 { get; set; }
        public Nullable<decimal> FAmt3 { get; set; }
        public string XBill { get; set; }
        public Nullable<decimal> XQty { get; set; }
        public string XTo { get; set; }
        public string XVehicleNum { get; set; }
    }
}
