//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class vm_PurchaseDetails
    {
        public string FItemCode { get; set; }
        public string FItemName { get; set; }
        public string FSpec { get; set; }
        public string FUnit { get; set; }
        public string FCateName { get; set; }
        public decimal FPrice { get; set; }
        public decimal FQty { get; set; }
        public decimal FAmount { get; set; }
        public string FBottle { get; set; }
        public Nullable<int> FBottleOweQty { get; set; }
        public Nullable<int> FBottleQty { get; set; }
        public int FCateId { get; set; }
        public string KeyId { get; set; }
        public Nullable<decimal> FReturnQty { get; set; }
        public Nullable<decimal> FRecycleQty { get; set; }
        public int FId { get; set; }
        public string FBottleName { get; set; }
        public string FBottleCode { get; set; }
        public Nullable<int> FCompanyId { get; set; }
        public string FMemo { get; set; }
        public string FWarehouseCode { get; set; }
        public string FT6Warehouse { get; set; }
        public string FNum { get; set; }
    }
}
