//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class vm_SalesReturnDetailsLog
    {
        public string FItemCode { get; set; }
        public string FStatus { get; set; }
        public string FItemName { get; set; }
        public string FSpec { get; set; }
        public string FUnit { get; set; }
        public Nullable<decimal> FPrice { get; set; }
        public Nullable<decimal> FQty { get; set; }
        public Nullable<decimal> FAmount { get; set; }
        public string FBottle { get; set; }
        public Nullable<int> FBottleOweQty { get; set; }
        public Nullable<int> FBottleQty { get; set; }
        public string KeyId { get; set; }
        public int FId { get; set; }
        public string FBottleName { get; set; }
        public string FBottleCode { get; set; }
        public string FMemo { get; set; }
        public string FUpdateBy { get; set; }
        public Nullable<System.DateTime> FUpdateDate { get; set; }
        public Nullable<int> FCompanyId { get; set; }
    }
}
