//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class vm_StockOut
    {
        public string KeyId { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public string FCode { get; set; }
        public string FName { get; set; }
        public string CreateBy { get; set; }
        public string FTypeName { get; set; }
        public string FMemo { get; set; }
        public Nullable<int> FType { get; set; }
        public int FCompanyId { get; set; }
        public string FItemCode { get; set; }
        public Nullable<decimal> FPrice { get; set; }
        public Nullable<decimal> FQty { get; set; }
        public Nullable<decimal> FAmount { get; set; }
    }
}
