//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class vm_TubePlanList
    {
        public string KeyId { get; set; }
        public int FCompanyId { get; set; }
        public string CreateBy { get; set; }
        public string FBill { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public string FItemCode { get; set; }
        public string FItemName { get; set; }
        public Nullable<int> FType { get; set; }
        public string FVehicleNum { get; set; }
        public string FTrailerNum { get; set; }
        public string FDriver { get; set; }
        public string FSupercargo { get; set; }
        public Nullable<decimal> FStartMileage { get; set; }
        public Nullable<decimal> FQty { get; set; }
        public Nullable<decimal> FPrice { get; set; }
        public Nullable<decimal> FAmount { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public string FMemo { get; set; }
        public Nullable<System.DateTime> FDepartureTime { get; set; }
        public Nullable<System.DateTime> FEndTime { get; set; }
        public Nullable<int> FFlag { get; set; }
        public Nullable<int> FStatus { get; set; }
        public string FSupplierCode { get; set; }
        public string FSupplierName { get; set; }
        public Nullable<decimal> FPurchasedPrice { get; set; }
        public Nullable<decimal> FPurchasedQty { get; set; }
        public Nullable<decimal> FPurchasedAmt { get; set; }
        public string FPurchasedDate { get; set; }
        public Nullable<decimal> FSupplierInW { get; set; }
        public Nullable<decimal> FSupplierInY { get; set; }
        public Nullable<decimal> FSupplierOutW { get; set; }
        public Nullable<decimal> FSupplierOutY { get; set; }
        public Nullable<decimal> FSupplierPayW { get; set; }
        public Nullable<decimal> FSupplierPayY { get; set; }
        public Nullable<decimal> FSupplierRecW { get; set; }
        public Nullable<decimal> FSupplierRecY { get; set; }
        public string F1Code { get; set; }
        public string F1Name { get; set; }
        public Nullable<System.DateTime> F1Date { get; set; }
        public Nullable<decimal> F1Price { get; set; }
        public Nullable<decimal> F1Qty { get; set; }
        public string F1Address { get; set; }
        public string F1Phone { get; set; }
        public string F1Linkman { get; set; }
        public string F1Time { get; set; }
        public Nullable<decimal> F1Amt { get; set; }
        public Nullable<decimal> F1InW { get; set; }
        public Nullable<decimal> F1InY { get; set; }
        public Nullable<decimal> F1OutW { get; set; }
        public Nullable<decimal> F1OutY { get; set; }
        public Nullable<decimal> F1PayW { get; set; }
        public Nullable<decimal> F1PayY { get; set; }
        public Nullable<decimal> F1RecW { get; set; }
        public Nullable<decimal> F1RecY { get; set; }
        public Nullable<decimal> FMarginEnd { get; set; }
        public Nullable<decimal> FMargin { get; set; }
        public Nullable<int> FDeleteFlag { get; set; }
        public Nullable<decimal> F1PQty { get; set; }
        public Nullable<decimal> F1Gross { get; set; }
        public Nullable<decimal> F1Packed { get; set; }
        public string KeyId1 { get; set; }
        public string KeyId2 { get; set; }
        public Nullable<decimal> FMileage { get; set; }
        public string FT6Warehouse { get; set; }
        public string FDistributionPoint { get; set; }
        public string FContainer { get; set; }
    }
}
