//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Service.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class vm_Unit
    {
        public string FCate { get; set; }
        public string FCode { get; set; }
        public string FName { get; set; }
        public string FAddress { get; set; }
        public string FLinkman { get; set; }
        public string FPhome { get; set; }
        public string FMoile { get; set; }
        public string FSpell { get; set; }
        public int FCompanyId { get; set; }
        public string FSubCateId { get; set; }
        public string FDistric { get; set; }
        public string FSalesman { get; set; }
    }
}
